version: "3.8"

services:
  realchat_backend:
    build: ./realchat_backend
    restart: always
    volumes:
      - ./realchat_backend:/app
      - sqlite_data:/app/db_data
      - static_volume:/app/staticfiles
    env_file:
      - ./realchat_backend/.env
    environment:
      - DATABASE_PATH=/app/db_data/db.sqlite3
    ports:
      - "8000:8000"
    networks:
      - app_network
    command: >
      sh -c "python manage.py collectstatic --noinput --clear &&
            python manage.py migrate &&
            gunicorn realchat.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - realchat_backend
    networks:
      - app_network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - realchat_backend
      - frontend
    networks:
      - app_network

volumes:
  - static_volume:/app/staticfiles
  - static_volume:/static

networks:
  app_network:
